name: process-items

on:
  push:
    branches:
      - master

jobs:
  process-items:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: foundryvtt/pf2e
          path: pf2e

      - name: Merge item files into one
        run: |
          jq --slurp 'map(.)' *.json > merged.json
        working-directory: pf2e/packs/data/equipment.db

      - uses: actions/upload-artifact@v2
        with:
          name: items
          path: pf2e/packs/data/equipment.db/merged.json

