name: publish-site

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  process-items:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: foundryvtt/pf2e
          path: pf2e

      - name: Merge item files into one
        run: |
          jq --slurp 'map(.)' *.json > merged.json
        working-directory: pf2e/packs/data/equipment.db

      - name: Copy items to primary directory
        run: |
          cp pf2e/packs/data/equipment.db/merged.json input.json

      - name: Process items
        run: |
          node scripts/process-items.js

      - uses: actions/upload-artifact@v3
        with:
          name: items-merged
          path: input-spells.json

      - uses: actions/upload-artifact@v3
        with:
          name: items-processed
          path: public/items.json

  publish-site:
    needs: [process-items]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: items-processed
          path: src/assets

      - name: Install node modules
        run: |
          npm install

      - name: Set production Heap id
        run: |
          sed -i 's/1591913402/1099409969/g' index.html

      - name: Build
        run: |
          npm run build

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: pf2eprintablecards
          SENTRY_PROJECT: pf2eprintablecards
        with:
          environment: production

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          token: ${{ secrets.TOKEN }}
